openapi: 3.0.3
info:
  title: AI JSON Extractor API
  description: >
    Upload a JSON schema and unstructured text file. The API uses a language model (e.g., GPT-4.1 or O4-Mini) to convert the text into a structured JSON object matching the schema.
    It will retry up to 3 times to fix validation errors before returning.
  version: "1.0.0"
  contact:
    name: Avijeet Palit
    email: avijeet.palit07@gmail.com

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /extract-json/:
    post:
      summary: Extract structured JSON from unstructured text
      operationId: extractJson
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - schema
                - text
              properties:
                schema:
                  type: string
                  format: binary
                  description: JSON Schema file (`.json`)
                text:
                  type: string
                  format: binary
                  description: Plaintext or BibTeX or resume text (`.txt`, `.bib`, `.pdf`)
                model:
                  type: string
                  default: gpt-4.1-2025-04-14
                  description: "Model to use. Options: `gpt-4.1-2025-04-14`, `o4-mini-2025-04-16`"
      responses:
        "200":
          description: Successfully extracted JSON
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                  token_estimate:
                    type: integer
                  attempts:
                    type: integer
                  json_result:
                    type: object
                    description: Final structured output adhering to schema
        "400":
          description: Bad request — invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "422":
          description: Failed after retries
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  session_id:
                    type: string
                  token_estimate:
                    type: integer

components:
  securitySchemes: {}
  schemas: {}
